name: stk_env
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python=3.10
  - scikit-learn
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - ipykernel
  - tqdm
  - transformers
  - yfinance
  - alpha_vantage
  - kagglehub
  - pip:
    - requests
    - streamlit
